### PR TITLE
Jenkinize for CI!

### PR DESCRIPTION
**Pull request by orospakr**
Does the builds/test runs inside Docker.

* Move from godeps to glide, which seems a better dep management
  solution and solved an issue where godep was tanking inside
  Docker/vboxsf.

GitHub CI integration not yet set up because we haven't exposed Jenkins to the public Internet.

### CODE REVIEW

**Comment by orospakr** [comment]
Excuse the spam from the vendor directory.  It was already there in the project, but I had to move it to a different dir and recreate the contents.  I know having deps in the repo is generically a code smell, but this is actually recommended in order to make `go get` work, important for reducing friction for users installing force.

**Comment by robertpeacock22** [comment]
Looks good, but involves a number of things none of which are my area of expertise. Maybe get another reviewer on this?

**Comment by orospakr** [comment]
hmm, not really! :D

**Comment by highbass** [comment]
LGTM

**Pull request merged**
